name: Cypress Parallel
author: Thomas Gamauf
description: >
  Tooling for executing Cypress tests in parallel without Cypress Dashboard.
branding:
  icon: "fast-forward"
  color: "orange"
inputs:
  working-directory:
    description: If provided, this is the path the Cypress config file is expected at.
    required: false
  follow-symbolic-links:
    description: Indicates whether to follow symbolic links.
    required: false
    default: true
  count-runners:
    description: Maximum number of runners that should be used.
    required: false
outputs:
  integration-tests:
    description: Integration test specs that have been found.
  component-tests:
    description: Component test specs that have been found.
runs:
  using: node16
  main: dist/index.js